project:
  type: website
  output-dir: docs

website:
  title: "FG-COMPASS"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - publication.qmd
      - download.qmd
      - developers.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto
editor: visual




