---
title: "Ovande Furtado JR"
sidebar: true
---

Dr. Furtado received a B.A. in Physical Education from the Federal University of Parana, Curitiba, PR - Brazil. He earned his M.S. and Ph.D. degrees in Motor Behavior from the University of Pittsburgh, PA. Dr. Furtado's line of research focuses on two main areas: (1) validation of observational models in psychomotor assessment instruments and (2) the relationship between motor skill competence, perceived motor competence, physical activity levels, and body composition.

### Education

Ph.D. in Motor Behavior, 2009 - University of Pittsburgh\
M.S. in Motor Behavior, 2004 - University of Pittsburgh\
B.A. in Physical Education K-12, 1998 - Federal University of Parana - Brazil

### Experience

**Associate Professor**\
Cal State Northridge, Northridge, CA\
2013 -- Present\
Teaches motor behavior and statistics courses.

**Associate Professor**\
Eastern Illinois University, Charleston, IL\
2007-2013\
Taught motor behavior and statistics courses.

**Physical Educator Teacher K-12**\
Falk Lab School, Pittsburgh, PA\
2006-2007\
Taught motor skill development for children K-12.

**Kinder Kinetics Movement Program Co-Director**\
University of Pittsburgh, Pittsburgh, PA\
2004-2007
