---
title: "Publications"
---

Mazzardo, O., Weis, B., Sampaio, A. A., Lima, D. F. de, Souza, D. C. de, & Furtado Jr, O. (2023). *Association between fundamental motor skill domains and physical fitness components in children aged 5 to 11 years* \[Manuscript in preparation\].

Perez, L., & Furtado Jr, O. (2024). Investigating Expert-Rater Agreement and Inter/Intra-Rater Reliability of Two Fundamental Movement Skills for the Locomotor Subscale of the FG-COMPASS. *Perceptual and Motor Skills*. <https://doi.org/10.1177/00315125241272720>

Bolin, M., & Furtado Jr, O. (2023). Examining the relationship between bmi, sex, and fundamental movement skill performance in low-income rural children. *Journal of Kinesiology & Wellness*, *12*(1). <https://doi.org/10.56980/jkw.v12i1.138>

Woolever, M., Furtado Jr., O., & Gallagher, J. D. (2023). *Collecting concurrent validity, expert-rater agreement, and inter/intra-rater reliability evidence for the FG-COMPASS* \[Manuscript in preparation\].

Furtado Jr, O., & Gallagher, J. D. (2018). Expert-Rater Agreement and Inter-/Intrarater Reliability for the Furtado--Gallagher Computerized Observational Movement Pattern Assessment System. *Perceptual and Motor Skills*, *125*(3), 423--437. <https://doi.org/10.1177/0031512518769205>

Mazzardo, O., Fontana, F. E., Furtado Jr, O., & Gallagher, J. D. (2018). The relationship of movement skills with habitual and organized physical activity in seven and eight-year-old children. *Pensar a Prática*, *21*(1). <https://doi.org/10.5216/rpp.v21i1.42360>

Furtado Jr, O., & Gallagher, J. D. (2012). The reliability of classification decisions for the Furtado-Gallagher Computerized Observational Movement Pattern Assessment System---FG-COMPASS. *Research Quarterly for Exercise and Sport*, *83*(3), 383--390. <https://doi.org/10.1080/02701367.2012.10599872>
